### ISSUE TITLE
No data in line 0 - mistake or intended?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [edwin-zvs/email-providers#6]
If I open the CVS file with my mobile phone, I see the following:

![Screenshot_20191130-233103_Firefox](https://user-images.githubusercontent.com/11881073/69906846-239c7880-13ca-11ea-94cb-b2ecb54029d7.jpg)

...if I open then the link, I come to the following page:
https://help.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data

So is the first empty line a mistake of intended ???

**Comment by drahosistvan** [comment]
@Tobias-B-Besemer this issue is related to Github's CSV rendering engine. The problem is, that this file has only one column. If the file has at least two columns, the rendering and searching works fine. You can check my test here: https://github.com/drahosistvan/email-providers/blob/csvtest/email-providers.csv

Maybe later the domain list will be extended with extra metadata, and this problem will disappear.
